[programs.devnet]
sola = "27LbaFMbP6Cn56aGvnDETZzU1WY8jJjT62TPq3jgWTvw"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/wleung/.config/solana/id.json"

[scripts]
test = "node tests/sola.js" 
